name: Uglify JavaScript

on:
  push:
    branches:
      - main

jobs:
  uglify:
    runs-on: ubuntu-22.04 # Explicitly set Ubuntu version

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm list terser # Verify terser is installed

      # Step 4: Debug environment (optional)
      - name: Debug Path
        run: echo $PATH

      # Step 5: Uglify JavaScript files
      - name: Uglify JS
        run: |
          mkdir -p dist
          npx terser src/*.js -o dist/app.min.js

      # Step 6: Push the uglified code to a branch
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Automated uglification"
          git push origin main:uglified-branch
