name: Uglify JavaScript

on:
  push:
    branches:
      - main

jobs:
  uglify:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install
          npm list terser

      # Step 4: Debug environment (optional)
      - name: Debug Environment
        run: |
          echo "Node.js version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Path: $PATH"
          ls -l ./node_modules/.bin

      # Step 5: Fix Permissions for terser
      - name: Fix Permissions for terser
        run: chmod +x ./node_modules/.bin/terser

      # Step 6: Uglify JavaScript files
      - name: Uglify JS
        run: |
          mkdir -p dist
          npx terser src/*.js -o dist/app.min.js

      # Step 7: Push the uglified code to a branch
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git checkout -B uglified-branch # Create or switch to the branch
          git add dist
          git commit -m "Automated uglification"
          git push -u origin uglified-branchs
